# Grants a subject permission to load OPA policies from an external source
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-opa
rules:
- apiGroups:
  - authorino.kuadrant.io
  resources:
  - authconfig-external-opa
  verbs:
  - use
